# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X < Formula
  desc "a simple and fast task runner"
  homepage "https://github.com/bambamboole/x"
  version "0.1.0-rc5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc5/x-0.1.0-rc5-darwin-amd64"
      sha256 "af54dfbdcc2dde0ad53525458389a969eeb58d187e0a0361b5512698a96bc8a3"

      def install
        bin.install "x-0.1.0-rc5-darwin-amd64" => "x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc5/x-0.1.0-rc5-darwin-arm64"
      sha256 "f2ec96e45dfac5766f706c410fc59e39bbe2bbb0ef160a5f37b2bd69e3608d25"

      def install
        bin.install "x-0.1.0-rc5-darwin-arm64" => "x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc5/x-0.1.0-rc5-linux-arm64"
      sha256 "e33aca2b65b68f53ae16fe4a0549013624f808f0f644017605a483ee5082f7bc"

      def install
        bin.install "x-0.1.0-rc5-linux-arm64" => "x"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc5/x-0.1.0-rc5-linux-amd64"
      sha256 "6be1cddfe0ea5501f026c42206e46158a1e2243b360e105a998e8fc207ae0104"

      def install
        bin.install "x-0.1.0-rc5-linux-amd64" => "x"
      end
    end
  end
end
